# Site settings
title: WINDJAMMERS LMF ULTRA CUP
tag_text: WINDJAMMERS LMF ULTRA CUP
description: Ce qui sépare l’homme de la bête, c’est le frisbee
url: "http://127.0.0.1:4000"
baseurl: ""

font-awesome-include: false # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]
